#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'crs-utils-py','console_scripts','joint_state_publisher'
__requires__ = 'crs-utils-py'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('crs-utils-py', 'console_scripts', 'joint_state_publisher')()
    )
